name: Spritz-Wine-TkG-AAGL
on:
  workflow_dispatch:
  push:
    tags:
      - 'wine-tkg-aagl*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build_type: "release"
            
    name: Build Wine (${{ matrix.build_type }})
    steps:
      - uses: actions/checkout@v4

      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ./ccache
          key: ccache-${{ matrix.build_type }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.build_type }}-

      - uses: docker/setup-buildx-action@v3.10.0
        with:
          driver: docker

      - name: Run build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Save ccache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ./ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spritz-wine-${{ matrix.build_type }}
          path: ./*.tar.xz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: spritz-wine-release
          path: ./artifacts/

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG="${{ github.ref_name }}"
          VERSION=$(echo "$TAG" | sed -n 's/^wine-tkg-aagl-\(v[0-9]\+\.[0-9]\+-[0-9]\+\)$/\1/p')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ./artifacts/*.tar.xz
          name: "Spritz-Wine-TkG-AAGL-${{ steps.extract_version.outputs.version }}"
          make_latest: true